2024-07-29 23:53:08,973 - ERROR - Ошибка при отправке сообщения: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong file identifier/HTTP URL specified
2024-07-29 23:57:58,217 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:57:58,222 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:58:02,129 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:58:02,132 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:58:06,786 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:58:06,788 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:58:12,224 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:58:12,228 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:58:14,329 - ERROR - Ошибка при отправке сообщения: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong file identifier/HTTP URL specified
2024-07-29 23:58:20,034 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:58:20,036 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:58:32,122 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:58:32,125 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:58:40,412 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:58:40,416 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:58:44,344 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:58:44,347 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:58:48,469 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:58:48,472 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:58:51,449 - ERROR - Ошибка при отправке сообщения: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: wrong file identifier/HTTP URL specified
2024-07-29 23:58:53,138 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:58:53,141 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:59:16,581 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:59:16,583 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:59:20,241 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:59:20,245 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:59:24,145 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:59:24,147 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:59:28,824 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:59:28,826 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-29 23:59:34,980 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-29 23:59:34,983 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:07:08,526 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:07:08,529 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:07:12,194 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:07:12,199 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:07:16,365 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:07:16,367 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:07:20,764 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:07:20,767 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:07:26,433 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:07:26,436 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:07:34,581 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:07:34,585 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:07:47,769 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:07:47,806 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:07:56,497 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:07:56,500 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:08:08,052 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:08:08,054 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:08:27,224 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:08:27,226 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:09:02,676 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:09:02,681 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:10:06,087 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:10:06,091 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-30 00:11:09,630 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-30 00:11:09,633 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DOWN\anonimBot\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

